### ISSUE TITLE
Version not set in project.deps.json when using project references

### ISSUE THREAD

**Issue by christianerbsmehl** [devlooped/GitInfo#148] opened 2021-03-18 15:06 UTC
I'm having some trouble getting GitInfo to work properly in following setup:
I have a solution with two projects. Both are individual NuGet packages and one of them has a project dependency on the other.
To leverage versioning I have a `Directory.Build.props` and `Directory.Build.targets` file in the root folder:

Directory.Build.props:

```xml
<Project>
  <PropertyGroup>
    <Authors>Christian Erbsmehl</Authors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version Condition="'$(Version)' == ''">42.42.42</Version>
  </PropertyGroup>

  <PropertyGroup Label="GitInfo">
    <GitCommitsIgnoreMerges>true</GitCommitsIgnoreMerges>
    <GitIgnoreBranchVersion>true</GitIgnoreBranchVersion>
    <GitIgnoreTagVersion>true</GitIgnoreTagVersion>
    <GitThisAssembly>false</GitThisAssembly>
  </PropertyGroup>

  <!-- This target is replaced by GitInfo when restored -->
  <Target Name="GitVersion" />
</Project>
```

Directory.Build.targets:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="SetVersions"
          BeforeTargets="PrepareForBuild;GetAssemblyVersion;GenerateNuspec;Pack"
          DependsOnTargets="GitVersion"
          Returns="$(Version)"
          Condition="'$(GitInfoImported)' == 'true' And '$(ExcludeRestorePackageImports)' != 'true'">

    <PropertyGroup>
      <GitBranch>$(GitBranch.Replace('/', '-'))</GitBranch>
      <!-- We don't build stable versions from feature branches. But when the version came from the branch, we leave it as-is. -->
      <GitSemVerDashLabel Condition="'$(GitBranch)' != 'master'">$(GitSemVerDashLabel)-$(GitBranch)</GitSemVerDashLabel>
    </PropertyGroup>

    <PropertyGroup>
      <GitSemVerDashLabel Condition="'$(GitSemVerDashLabel)' != '' and '$(GitCommits)' != '0'">$(GitSemVerDashLabel).$(GitCommits)</GitSemVerDashLabel>

      <!-- Regular semver for stable builds -->
      <PackageVersion Condition="'$(GitSemVerDashLabel)' == ''">$(GitSemVerMajor).$(GitSemVerMinor).$(GitSemVerPatch)</PackageVersion>

      <!-- Fixed prerelease version for non-stable builds -->
      <PackageVersion Condition="'$(GitSemVerDashLabel)' != ''">$(GitBaseVersionMajor).$(GitBaseVersionMinor).$(GitBaseVersionPatch)$(GitSemVerDashLabel)</PackageVersion>

      <Version>$(PackageVersion)</Version>
    </PropertyGroup>
  </Target>
</Project>
```

When building, all version information is set correctly in both assemblies. But in the `.deps.json` file (and the nuspec of the generated nuget package) of the project with the project dependency, the dependent assemby is referenced with version `42.42.42` (as declared in `Directory.Build.props`) and not the correct version generated by GitInfo.

Any ideas? Help would be greatly appreciated! I can provide a sample if needed.

**Comment by kzu** [comment] 2021-03-18 23:52
You should run `dotnet restore -bl` and inspect the binlog to determine what target to add to the `BeforeTargets` on that `SetVersions` so that it runs before the deps file is generated. It's most likely running to late (or not running at all) during a restore.

**Comment by christianerbsmehl** [comment] 2021-03-19 10:03
The `*.deps.json` files are generated on build not on restore (`GenerateBuildDependencyFile` target). But: They are generated based on the `project.assets.json` files which are generated on restore . This is bad, because this happens really early in the restore process, before GitInfo is restored and available. I have no idea how to work around this limitation 😕

**Comment by kzu** [comment] 2021-03-19 17:31
Perhaps you don't need GitInfo at all. I'm not using it in [ThisAssembly](https://github.com/devlooped/ThisAssembly) project, for example and things work just fine with the OOB stuff (plus Microsoft.SourceLink.GitHub, in my case). You can inspect the build script from that repo. It's basically my template from https://github.com/devlooped/oss.

**Comment by kzu** [comment] 2021-05-17 15:56
Closing for now since there is not enough information to reproduce (i.e. a binlog), also, it's not obvious what effect or issue that project.deps.json causes (it's not clear to me why it matters at all).

**Closed by kzu** 2021-05-17 15:56 UTC
Labels: need info
